export const ActionTypes = {

    SET_RESTAURANTS: "SET_RESTAURANTS",
    SET_FIFTY_RESTAURANTS: "SET_FIFTY_RESTAURANTS",
    SET_SELECTED_RESTAURANT: "SET_SELECTED_RESTAURANT",
    SET_USER_LOCATION: "SET_USER_LOCATION",
    SET_SELECTED_PROVIDER: "SET_SELECTED_PROVIDER",
    SET_FILTERֹֹֹ_TYPE: "SET_FILTERֹֹֹ_TYPE",

}