export const ActionTypes = {

    SET_RESTAURANTS: "SET_RESTAURANTS",
    SET_FIFTY_RESTAURANTS: "SET_FIFTY_RESTAURANTS",
    SET_SELECTED_RESTAURANT: "SET_SELECTED_RESTAURANT",
    SET_USER_LOCATION: "SET_USER_LOCATION",
    SET_SELECTED_PROVIDER: "SET_SELECTED_PROVIDER",
    SET_FILTERֹֹֹ_TYPE: "SET_FILTERֹֹֹ_TYPE",
    SET_FILTERֹֹֹED_BY_CATEGORY: "SET_FILTERֹֹֹED_BY_CATEGORY",
    SET_SUB_FILTERֹֹֹ_TYPE: "SET_SUB_FILTERֹֹֹ_TYPE",
    SET_CURRENT_CITY: "SET_CURRENT_CITY",
    SET_USER_LAT_LON: "SET_USER_LAT_LON",

}